app:
  listen:
    host: 0.0.0.0
    port: 8000
  logging:
    destination: /home/pi/dev/logs/sensorkit-monitor.log
    log-level: debug
    format: '%(levelname)s %(asctime)s : %(message)s'
  metrics:
    encoding: prometheus
    labels:
      room: office
      version: 0.0.1
sensor-environment:
  altimeter-calibration:
    interval-time: 10
    interval-units: minutes
  indoors: true
